#!/bin/bash

if ! type -P svn > /dev/null; then
    echo "You should install subversion package to use $0"
elif [ x$1 == "x" ]; then
    echo "Usage: $0 <pkgname>"
else
    svn co http://svn.mandriva.com/svn/packages/cooker/$1/current/ mandriva-$1-current
fi
