#!/bin/bash
#
# A simple script that parses kernel modules and prints missing firmwares
#

MODULELIST=`modprobe -l -n|sed -e 's/.*\///' -e 's/.ko$//'`
FIRMWARELIST=`modinfo -F firmware $MODULELIST`


for i in $FIRMWARELIST;
do
    test -f /lib/firmware/$i || echo "missing $i"
done


