#!/usr/bin/python
# -*- coding: utf-8 -*-

import piksemel
import bz2
import sys
import os


def getXmlData(_file):
    if os.path.exists(_file):
        return piksemel.parse(_file)
    elif os.path.exists("%s.bz2" % _file):
        indexdata = bz2.decompress(file("%s.bz2" % _file).read())
        return piksemel.parseString(indexdata)
    else:
        print "%s not found" % indexfile
        sys.exit(1)

def parseXmlData(_index):
    pkglist = []
    hasSpecFile = _index.getTag("SpecFile")

    if hasSpecFile:
        for i in _index.tags("SpecFile"):
            parent = i.getTag("Source")
            pkglist.append(parent.getTagData("Name"))
    else:
        for parent in _index.tags("Package"):
            pkglist.append(parent.getTagData("Name"))

    pkglist.sort()
    return pkglist

def getPackageList(indexfile):
    xmldata = getXmlData(indexfile)
    packages = parseXmlData(xmldata)

    return packages

def printListDifference(list1, list2):
    listdiff = filter(lambda x:x not in list1,list2)

    for i in listdiff:
        print i

def usage():
    print "prints package differences in pisi index files"
    print "usage: %s <old-index>  <new-index>" % sys.argv[0]
    print
    sys.exit(0)

if __name__ == "__main__":
    try:
        indexOld = sys.argv[1]
        indexNew = sys.argv[2]
    except IndexError:
        usage()

    oldpackages = getPackageList(indexOld)
    newpackages = getPackageList(indexNew)

    printListDifference(oldpackages, newpackages)


