#!/usr/bin/python
# -*- coding: utf-8 -*-

# Find packages with no translations.xml and print them by packagers

import os
import pisi

# Do not put '/' to the end of develDir string
# e.g. "/mnt/Pardus_SVN" is ok but "/mnt/Pardus_SVN/" is not!!..
develDir = "."
d = {}

for root, dirs, files in sorted(os.walk(develDir)):
    if "pspec.xml" in files and "translations.xml" not in files:
        spec = pisi.specfile.SpecFile(os.path.join(root, "pspec.xml"))
        p_name= spec.source.name
        packager_name = str(spec.source.packager.name)
        if packager_name in d:
            d[str(packager_name)].append(p_name)
        else:
            d[str(packager_name)] = [p_name]

for i in d:
    if len(d[i]):
        print i, "(%s)" % len(d[i])
        for j in d[i]:
            print "    ", j
        print

