#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys
import pisi

def main():
    install_db = pisi.db.installdb.InstallDB()
    packages = []

    # Update index
    os.system("pisi ur")

    # filter out out-of-repo packages
    for package in install_db.list_installed_with_build_host("localhost"):
        try:
            package_info = pisi.api.info_name(package)
        except:
            pass
        else:
            packages.append(package)

    if packages:
        print "\nThe following packages will be reinstalled:"
        print "\n".join(packages)

        while True:
            try:
                print "\nDo you want to continue? (y/n)",
                input = raw_input()
                if input.startswith("n"):
                    return 1
                elif input.startswith("y"):
                    os.system("pisi install %s --reinstall -vd" % " ".join(packages))
                    return 0
            except KeyboardInterrupt:
                return 1

if __name__ == "__main__":
    sys.exit(main())
