#!/bin/bash

# in order to list the paths
# find -name pspec.xml | xargs grep -B2 '<Email><packager email></Email>' | grep Packager > <packagelistfile>

#in order to change all files run the below script

#!/usr/bin/python
# -*- coding: utf-8 -*-

#import os

#f = open('<packagelistfile>')
#lines = f.readlines()
#f.close()

#for line in lines:
#    print line
#    os.system('./takeover %s' %line)

# Usage: takeover pardus/devel/kernel/kernel/pspec.xml

NAME="YOUR NAME"
EMAIL="YOUR EMAIL"

sed -i "/<Packager>$/{
N
N
N
s/<Name>.*<\/Name>\n/<Name>$NAME<\/Name>\n/
s/<Email>.*<\/Email>\n/<Email>$EMAIL<\/Email>\n/
}" $1
